Liter = float
Watt = float
JoulePerLiterKelvin = float
Second = float
LiterPerSecond = float
Celsius = float
MeterSquared = float
WattPerMeterSquared = float
Joule = float
JoulePerKelvin = float
KiloWatt = float
HectoPascal = float
MeterPerSecond = float
Percentage = float
Degree = float
Bar = float
BatteryAlarm = int  # 0: no Alarm, 1: Warning, 2: Alarm
