services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto
    platform: linux/arm/v8
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/local-config
      - ./certs/ISRG_ROOT_X1.crt:/mosquitto/certs/ca.crt
    networks:
      - power_hub_control
    logging: &logging
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"

    command: >
      sh -c "cp /local-config/mosquitto.conf /mosquitto/config/mosquitto.conf &&
             echo 'remote_password ${PROD_MQTT_PASSWORD}' >> /mosquitto/config/mosquitto.conf &&
             mosquitto -c /mosquitto/config/mosquitto.conf"

    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-i",
          "healthcheck",
          "-W",
          "3"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  control:
    depends_on:
      mosquitto:
        condition: service_healthy
    image: python-control-app:latest-armv8
    platform: linux/arm/v8
    container_name: control
    command: "energy_box_control.power_hub_control"
    networks:
      - power_hub_control
    env_file:
      - ./.env
    restart: on-failure
    logging: *logging

networks:
  power_hub_control: