services:
  vernemq:
    image: vernemq:latest-armv7
    container_name: vernemq
    platform: linux/arm/v7
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${CERTIFICATE_DIR}/ISRG_ROOT_X1.crt:/etc/ssl/vernemq/cafile.crt:ro
    networks:
      - power_hub_control
    env_file:
      - .env
    environment:
      DOCKER_VERNEMQ_USER_power-hub: '${PROD_MQTT_PASSWORD}'
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_LISTENER__WS__DEFAULT: "0.0.0.0:9001"
      DOCKER_VERNEMQ_PLUGINS__VMQ_BRIDGE: "on" #https://docs.vernemq.com/configuring-vernemq/bridge
      DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0: "${PROD_VERNEMQ_URL}"
      DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__TOPIC__1: "power_hub/* out 1"
      DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__username: "power-hub"
      DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__password: "${PROD_MQTT_PASSWORD}"
      DOCKER_VERNEMQ_VMQ_BRIDGE__SSL__BR0__cafile: "/etc/ssl/vernemq/cafile.crt"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/health" ]
      interval: 60s
      timeout: 60s
      retries: 10

  control:
    depends_on:
      vernemq:
        condition: service_healthy
    image: python-control-app:latest-armv7
    platform: linux/arm/v7
    container_name: control
    command: "energy_box_control.power_hub_control"
    networks:
      - power_hub_control
    env_file:
      - .env
    restart: on-failure:5

networks:
  power_hub_control:
