name: PowerHub Demo
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version-file: "./apps/demo/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: apps/demo/pnpm-lock.yaml

      - run: pnpm install
        working-directory: apps/demo

      - run: pnpm lint
        working-directory: apps/demo

      - run: pnpm type-check
        working-directory: apps/demo

      - run: pnpm test:unit
        working-directory: apps/demo

  deploy:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Extract alias
        shell: bash
        run: |
          export BRANCH=${GITHUB_REF#refs/heads/}
          echo alias=$(ruby -e "puts '$BRANCH'.tr('/_', '-').chomp('-')[0..27]") >> $GITHUB_OUTPUT
        id: extract-alias

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          initial-status: success
          environment-url: http://${{steps.extract-alias.outputs.alias}}.power-hub.pages.dev
          environment: ${{steps.deploy.outputs.environment}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version-file: "./apps/demo/.nvmrc"

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        working-directory: ./apps/demo
        run: pnpm install

      - name: Lint check
        working-directory: ./apps/demo
        run: pnpm lint --max-warnings 0

      - name: Generate website
        working-directory: ./apps/demo
        run: pnpm build
        env:
          VITE_API_BEARER_TOKEN: ${{secrets.POWER_HUB_API_TOKEN}}

      - name: Deploy preview
        id: deploy
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: power-hub
          directory: "./apps/demo/dist"
          wranglerVersion: 3
